'use strict';const crypto=require('crypto');
const states={detected:['triaged','dismissed'],triaged:['assessment_in_progress','dismissed'],assessment_in_progress:['approval_pending','needs_information'],needs_information:['assessment_in_progress','dismissed'],approval_pending:['approved','needs_information','rejected'],approved:['published'],published:['remediation_in_progress','superseded'],remediation_in_progress:['remediated','published'],remediated:['superseded'],dismissed:[],rejected:[],superseded:[]};
const grants={analyst:['detected:triaged','triaged:assessment_in_progress','assessment_in_progress:approval_pending','needs_information:assessment_in_progress'],reviewer:['assessment_in_progress:needs_information','approval_pending:approved','approval_pending:needs_information','approval_pending:rejected'],publisher:['approved:published','published:remediation_in_progress','remediation_in_progress:remediated','remediation_in_progress:published'],records_manager:['published:superseded','remediated:superseded'],admin:['*']};
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}const digest=v=>crypto.createHash('sha256').update(canonical(v)).digest('hex');
function ingest(change){for(const k of ['sourceId','sourceUri','publisher','jurisdiction','effectiveAt','publishedAt','retrievedAt','version','content'])if(!change[k])throw new Error(`${k} required`);if(!/^https:\/\//.test(change.sourceUri))throw new Error('authoritative HTTPS source URI required');return{...change,contentDigest:digest(change.content),provenanceDigest:digest({sourceId:change.sourceId,sourceUri:change.sourceUri,publisher:change.publisher,jurisdiction:change.jurisdiction,effectiveAt:change.effectiveAt,publishedAt:change.publishedAt,version:change.version})}}
function detect(previous,next){const incoming=ingest(next);if(!previous)return{kind:'created',incoming};if(previous.sourceId!==incoming.sourceId)throw new Error('source mismatch');if(previous.contentDigest===incoming.contentDigest&&previous.version===incoming.version)return{kind:'unchanged',incoming};return{kind:'changed',incoming,previousDigest:previous.contentDigest}}
function mapImpacts(input){if(!input.changeId||!input.ownerId)throw new Error('change and owner required');if(!input.citations?.length)throw new Error('citation required');const impacts=input.impacts||[];if(!impacts.length)throw new Error('at least one impact required');const errors=[];for(const item of impacts){if(!item.id||!item.targetType||!item.targetId)errors.push('unbound impact');if(!['policy','control','product','contract','process','system'].includes(item.targetType))errors.push(`unsupported target:${item.id}`);if(!item.ownerId)errors.push(`owner:${item.id}`);if(!item.obligation)errors.push(`obligation:${item.id}`);if(item.deadlineRequired&&!item.deadline)errors.push(`deadline:${item.id}`);if(!['low','medium','high','critical'].includes(item.riskRating))errors.push(`risk:${item.id}`)}return{passed:errors.length===0,releaseable:false,errors,impactDigest:digest(input)}}
function transition(item,to,actor){if(!states[item.status]?.includes(to))throw new Error(`invalid transition ${item.status} -> ${to}`);const allowed=grants[actor.role]||[];if(!allowed.includes('*')&&!allowed.includes(`${item.status}:${to}`))throw new Error('role cannot perform transition');if(['approved','published'].includes(to)&&(String(actor.id)===String(item.ownerId)||String(actor.id)===String(item.assessorId)))throw new Error('segregation of duties violation');if(['approval_pending','approved','published'].includes(to)&&!item.evaluationPassed)throw new Error('scenario evaluation must pass');return true}
function evaluate(input){const errors=[];if(!input.citations?.length)errors.push('citations');for(const c of input.citations||[])if(!c.sourceUri||!c.sourceVersion||!c.contentDigest)errors.push(`citation:${c.id}`);for(const o of input.obligations||[]){if(!o.ownerId)errors.push(`owner:${o.id}`);if(o.deadlineRequired&&!o.deadline)errors.push(`deadline:${o.id}`);if(!['low','medium','high','critical'].includes(o.riskRating))errors.push(`risk:${o.id}`)}if(!input.obligations?.length)errors.push('obligations');return{passed:errors.length===0,errors,evaluationDigest:digest(input)}}
function authorize(role,action){const matrix={viewer:['read','export_redacted'],analyst:['read','triage','assess'],reviewer:['read','review','approve'],publisher:['read','publish','remediate'],records_manager:['read','hold','retention','export_audit'],admin:['read','configure_roles']};if(!matrix[role]?.includes(action))throw new Error('forbidden');return true}
function retention(record,now=new Date()){if(record.legalHold)return{action:'retain',reason:'legal_hold'};if(!record.retainUntil)return{action:'review'};return Date.parse(record.retainUntil)<=now.getTime()?{action:'eligible_for_controlled_deletion'}:{action:'retain'}}
module.exports={states,canonical,digest,ingest,detect,mapImpacts,transition,evaluate,authorize,retention};
