const base = process.env.SMOKE_BASE_URL || 'http://127.0.0.1:5207';
const analystEmail = process.env.SMOKE_ANALYST_EMAIL, analystPassword = process.env.SMOKE_ANALYST_PASSWORD;
const managerEmail = process.env.SMOKE_MANAGER_EMAIL, managerPassword = process.env.SMOKE_MANAGER_PASSWORD;
const adminEmail = process.env.ADMIN_EMAIL, adminPassword = process.env.ADMIN_PASSWORD;
if (![analystEmail,analystPassword,managerEmail,managerPassword,adminEmail,adminPassword].every(Boolean)) throw new Error('Governed smoke role credentials are required');
async function login(email, password) { const response = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) throw new Error(`login ${response.status}`); return response.headers.get('set-cookie').split(';')[0]; }
async function call(path, cookie, method, body) { const response = await fetch(`${base}${path}`, { method, headers: { cookie, 'content-type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const text = await response.text(); const data = text ? JSON.parse(text) : {}; if (!response.ok) throw new Error(`${path} ${response.status} ${JSON.stringify(data)}`); return data; }
async function status(path, cookie, method, body) { return (await fetch(`${base}${path}`, { method, headers: { cookie, 'content-type': 'application/json' }, body: body ? JSON.stringify(body) : undefined })).status; }
const analyst = await login(analystEmail, analystPassword); const manager = await login(managerEmail, managerPassword); const admin = await login(adminEmail, adminPassword); const unique = Date.now().toString();
const change = await call('/api/governed/regulatory-change', analyst, 'POST', { sourceId: `reg-${unique}`, sourceUri: 'https://regulator.example/rule', publisher: 'Regulator', jurisdiction: 'US', effectiveAt: '2026-08-01T00:00:00Z', publishedAt: '2026-07-01T00:00:00Z', retrievedAt: '2026-07-19T00:00:00Z', sourceVersion: 'v1', content: { rule: 'must' }, ownerId: 'owner@example.test' });
if (await status('/api/governed/regulatory-change', manager, 'POST', {}) !== 403) throw new Error('ingestion RBAC failure path did not reject manager');
if (await status('/api/governed/regulatory-change', analyst, 'GET') !== 403) throw new Error('audit export RBAC failure path did not reject analyst');
if (await status('/api/governed/regulatory-change', analyst, 'POST', { sourceId: 'bad', sourceUri: 'https://regulator.example/bad', publisher: 'Regulator', jurisdiction: 'US', effectiveAt: 'not-a-date', publishedAt: 'not-a-date', retrievedAt: 'not-a-date', sourceVersion: 'v1', content: 'bad', ownerId: 'owner' }) !== 400) throw new Error('invalid source dates were accepted');
const recordsControl = await call('/api/governed/regulatory-change', admin, 'PATCH', { id: change.id, action: 'set_records_control', legalHold: true, retainUntil: '2028-01-01T00:00:00Z', rationale: 'Preserve evidence for active legal matter' }); if (!recordsControl.legal_hold) throw new Error('legal hold was not persisted');
await call('/api/governed/regulatory-change/impact', analyst, 'POST', { changeId: change.id, targetType: 'policy', targetId: 'POL-1', ownerId: 'remediator@example.test', obligation: 'Update the release policy', deadline: '2026-07-31T00:00:00Z', riskRating: 'high' });
const evaluation = await call('/api/governed/regulatory-change/evaluate', analyst, 'POST', { changeId: change.id, scenarioId: 'publication', citations: [{ sourceUri: change.source_uri, sourceVersion: change.source_version, contentDigest: change.content_digest, locator: '§1' }] }); if (!evaluation.passed) throw new Error('evaluation did not pass');
for (const [cookie, toStatus, rationale] of [[analyst,'triaged','Initial triage complete'],[analyst,'assessment_in_progress','Assessment has started'],[analyst,'approval_pending','Impact assessment complete'],[manager,'approved','Independent approval complete'],[admin,'published','Publication criteria satisfied']]) await call('/api/governed/regulatory-change', cookie, 'PATCH', { id: change.id, toStatus, rationale });
const exported = await call('/api/governed/regulatory-change', manager, 'GET'); if (!exported.records.some(record => record.change_id === change.id)) throw new Error('decision missing from audit export');
console.log('Governed regulatory-change API smoke passed');
